Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 140
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - config.ru
    - spec/spec_helper.rb
